# Visualize Phylogenetic Tree with Metadata

```{r}
library(ggplot2)
library(ggtree)
library(readxl)
library(dplyr)
library(tidyr)
library(stringr)
```


```{r}
uncc_colors <- c(
  ## All in C colors
  "#005035", ## Charlotte Green
  "#A49665", ## Niner Gold
  "#F1E6B2", ## Jasper
  "#899064", ## Pine Green
  "#802F2D", ## Clay Red
  "#007377",  ## Sky Blue
  
  ## Others
  "#717C7D", ## 444C (Grey)
  "#72246C", ## 255C (Purple)
  "#006BA6", ## 307C (Blue)
  "#DF4661", ## 198C
  "#FFB81C", ## 1235C
  "#696158"  ## 405C
  
)
```


## 164 Taxa Tree

### Load Data

```{r}
tree <- ape::read.nexus("164_tree/tree0.tnt.nex")
metadata <- read_excel("../../../Experiments.xlsx", sheet = "Antigens")
results <- read_excel("../../../Experiments.xlsx", sheet = "Experiments")
```


## Append Metadata

```{r}
tip_meta <- tip_labels %>%
  left_join(metadata, by = "antigen_id")

tree_df <- data.frame(node = 1:length(tree$tip.label),
                      tip_label = tree$tip.label) %>% 
  left_join(metadata, by = c("tip_label" = "antigen_id"))

tree$antigen_host_order <- tree_df$antigen_host_order 
```

### Make VDW Results Matrix

```{r}
# genotype_file <- system.file("examples/Genotype.txt", package="ggtree")
# genotype <- read.table(genotype_file, sep="\t", stringsAsFactor=F)
# colnames(genotype) <- sub("\\.$", "", colnames(genotype))
# 
# genotype

vdw_df <- results %>% 
  select(antibody_id, antigen_id, vdw_best) %>% 
  pivot_wider(names_from = antibody_id, values_from = vdw_best) %>% 
  tibble::column_to_rownames(var="antigen_id") %>% 
  select(order(colnames(.))) %>% 
  mutate(average = rowMeans(pick(where(is.numeric))))
  

vdw_df

```


### Visualize the Base Tree

```{r}
base_tree_plot <- ggtree(tree,
                         # layout="circular", 
                         layout="fan", open.angle=30,
                         # ladderize = FALSE,
                         # branch.length = "none",
                         # continuous = 'colour',
                         size=1
                         ) %<+% 
    metadata +
  geom_tiplab(size=2, align=TRUE, linesize=.5) # +
  # geom_text(aes(label=node), hjust=.3) +
  # aes(color=antigen_collection_location_continent) + 
  # scale_color_gradient(colours=c("red", 'orange', 'green', 'cyan', 'blue')) +
  # geom_tippoint(aes(color=antigen_host_order)) +
  # coord_flip() +
  # scale_x_reverse() #+
  # theme(color = "Host Order"
  #       shape = "Representative Sequence")
  # geom_tiplab(hjust = -.1)
  # theme(legend.position = "none")


base_tree_plot
```


## Add Heatmap to Tree

```{r}
gheatmap(base_tree_plot,
         vdw_df,
         offset=9, width=1, 
        colnames=TRUE,
        colnames_angle = 90,
        hjust = 1,
        font.size = 3,
        legend_title="Best van der Waals Energy") +
    scale_x_ggtree() +
  scale_fill_viridis_c(option = "plasma")
```

## 18K Tree

### Load Data

```{r}
tree_18k <- ape::read.nexus("18k_tree/tree0.tnt.nex")

metadata_18k <- read_excel("../../../Experiments.xlsx", sheet = "Full Antigen Metadata") %>% 
  mutate(Accession = antigen_id) %>% 
  replace_na(list(#antigen_host_class = "Not Specified",
                  antigen_host_order = "Not Specified",
                  antigen_collection_location_continent = "Not Specified"))

## Filter to taxa actually in the tree
metadata_18k_filtered <- metadata_18k %>% 
  filter(antigen_id %in% tree_18k$tip.label) %>% 
  mutate(label = antigen_id)

## Add metadata to tree
tree_18k_withmetadata <- full_join(tree_18k, metadata_18k_filtered, by = 'label')

# write.csv(metadata_18k_filtered, "metadata_18k_filtered.csv")
# write.beast(tree_18k_withmetadata, "18k_tree/tree0_w_meta_beast.nhx")
```


```{r}
class_tree <- ggtree(tree_18k_withmetadata,
       aes(color=antigen_host_class),
       # aes(color=antigen_collection_year),
       # layout = 'circular',
       # layout="fan", open.angle=180,
       layout = "rectangular",
       # ladderize = FALSE,
       # continuous = 'colour',
       size=0.1) +
  # coord_flip() +
  # scale_y_reverse() +
  geom_tippoint(size = 2, aes(colour=antigen_host_class)) +
  geom_tiplab(size = 1, color='black', hjust = 0.75) +
  # geom_nodelab(size=3, color="red")+
  # geom_hilight(mapping=aes(subset = node %in% tree_18k_withmetadata@data$node,
  #                          fill=antigen_host_class),
  #              alpha = .8) +
  labs(color = "Host Class") +
  scale_color_manual(values = uncc_colors) +
  # scale_color_brewer(palette = "Set1") +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal"
  )
```

```{r}
# node_id = 21495 ## Most distant clade
# node_id = 21480
node_id = 21481

nn <- tidytree::offspring(tree_18k_withmetadata, node_id, self_include=TRUE)

class_tree +
  ggforce::facet_zoom(xy = node %in% nn, zoom.size = 0.75)
```

```{r}
plotly::ggplotly(class_tree)
```



```{r}
library(strainhub)

## Check for missing taxa
setdiff(tree_18k$tip.label, metadata_18k$Accession)

## Check to See Which States are available by which to generate the network
list_states(tree_18k,
            metadata_18k,
            treeType = "parsimonious")
```

### Make Transmission Network

#### Continent

```{r}
continent_graph <- make_transnet(tree_18k,
                                 metadata_18k,
                                 columnSelection = "antigen_collection_location_continent",
                                 centralityMetric = 6,
                                 treeType = "parsimonious")

# continent_graph

## Using the graph object from before...
library(visNetwork)

nodes <- continent_graph$x$nodes %>%
  mutate(shape = "dot",
         color = "grey",
         font.size = 20)

## Define new edge colors
colors <- randomcoloR::distinctColorPalette(k = nrow(continent_graph$x$edges))

edges <- continent_graph$x$edges %>%
  mutate(arrows = "to",
         smooth = TRUE,
         color = colors,
         width = ifelse(value == 1, 1, 4),
         value = NULL)

## Generate the custom network using `visNetwork`
visNetwork(nodes, edges) %>%
  visOptions(nodesIdSelection = list(enabled = TRUE)) %>% 
  visPhysics(repulsion=list(
    nodeDistance=1000
  ),
  enabled=FALSE)



# continent_geodata <- read.csv("continent_geodata.csv")

# continent_map <- make_map(continent_graph,
#                          continent_geodata,
#                          columnSelection = "antigen_collection_location_continent",
#                          basemapLayer = "Gray",
#                          showLabels = TRUE)

# continent_map
```

#### Host Class

```{r}
class_graph <- make_transnet(tree_18k,
                       metadata_18k,
                       columnSelection = "antigen_host_class",
                       centralityMetric = 6,
                       treeType = "parsimonious")

class_graph
```